package com.tiancheng.homework.mapper;

import com.tiancheng.homework.domain.Examinee;
import com.tiancheng.homework.domain.ExamineeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ExamineeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinee
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    long countByExample(ExamineeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinee
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    int deleteByExample(ExamineeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinee
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    int deleteByPrimaryKey(Integer idExaminee);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinee
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    int insert(Examinee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinee
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    int insertSelective(Examinee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinee
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    List<Examinee> selectByExample(ExamineeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinee
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    Examinee selectByPrimaryKey(Integer idExaminee);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinee
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Examinee record, @Param("example") ExamineeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinee
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    int updateByExample(@Param("record") Examinee record, @Param("example") ExamineeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinee
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    int updateByPrimaryKeySelective(Examinee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examinee
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    int updateByPrimaryKey(Examinee record);

    @Select("select * from examinee where idExaminee=#{id}")
    Examinee selectById(@Param("id") int id);

    @Select("select password from examinee where (schoolnum=#{sn} and number=#{number})")
    String selectLogin(@Param("sn") String sn, @Param("number") String number);
}