package com.tiancheng.homework.mapper;

import com.tiancheng.homework.domain.Process;
import com.tiancheng.homework.domain.ProcessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 16 20:59:44 CST 2018
     */
    long countByExample(ProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 16 20:59:44 CST 2018
     */
    int deleteByExample(ProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 16 20:59:44 CST 2018
     */
    int deleteByPrimaryKey(Integer idprocess);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 16 20:59:44 CST 2018
     */
    int insert(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 16 20:59:44 CST 2018
     */
    int insertSelective(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 16 20:59:44 CST 2018
     */
    List<Process> selectByExample(ProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 16 20:59:44 CST 2018
     */
    Process selectByPrimaryKey(Integer idprocess);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 16 20:59:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") Process record, @Param("example") ProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 16 20:59:44 CST 2018
     */
    int updateByExample(@Param("record") Process record, @Param("example") ProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 16 20:59:44 CST 2018
     */
    int updateByPrimaryKeySelective(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 16 20:59:44 CST 2018
     */
    int updateByPrimaryKey(Process record);

    @Select("select * from process")
    List<Process> selectAll();
}