package com.tiancheng.homework.mapper;

import com.tiancheng.homework.domain.Richeng;
import com.tiancheng.homework.domain.RichengExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface RichengMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table richeng
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    long countByExample(RichengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table richeng
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    int deleteByExample(RichengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table richeng
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    int deleteByPrimaryKey(Integer idricheng);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table richeng
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    int insert(Richeng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table richeng
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    int insertSelective(Richeng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table richeng
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    List<Richeng> selectByExample(RichengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table richeng
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    Richeng selectByPrimaryKey(Integer idricheng);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table richeng
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") Richeng record, @Param("example") RichengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table richeng
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    int updateByExample(@Param("record") Richeng record, @Param("example") RichengExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table richeng
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    int updateByPrimaryKeySelective(Richeng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table richeng
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    int updateByPrimaryKey(Richeng record);

    @Select("select * from richeng")
    List<Richeng> selectAll();
}