package com.tiancheng.homework.mapper;

import com.tiancheng.homework.domain.Server;
import com.tiancheng.homework.domain.ServerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    long countByExample(ServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    int deleteByExample(ServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    int deleteByPrimaryKey(Integer idserver);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    int insert(Server record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    int insertSelective(Server record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    List<Server> selectByExample(ServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    Server selectByPrimaryKey(Integer idserver);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") Server record, @Param("example") ServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    int updateByExample(@Param("record") Server record, @Param("example") ServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    int updateByPrimaryKeySelective(Server record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    int updateByPrimaryKey(Server record);

    @Select("select * from server")
    List<Server> selectAll();
}