package com.tiancheng.homework.domain;

public class Exam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.examID
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private Integer examID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.time
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.place
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.number
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.type
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.examID
     *
     * @return the value of exam.examID
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public Integer getExamID() {
        return examID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.examID
     *
     * @param examID the value for exam.examID
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setExamID(Integer examID) {
        this.examID = examID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.time
     *
     * @return the value of exam.time
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.time
     *
     * @param time the value for exam.time
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.place
     *
     * @return the value of exam.place
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.place
     *
     * @param place the value for exam.place
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.number
     *
     * @return the value of exam.number
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.number
     *
     * @param number the value for exam.number
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.type
     *
     * @return the value of exam.type
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.type
     *
     * @param type the value for exam.type
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}