package com.tiancheng.homework.domain;

public class Grade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.idExaminee
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private Integer idExaminee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.idperson
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private String idperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.name
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.subject1
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private String subject1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade1
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private String grade1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.subject2
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private String subject2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade2
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private String grade2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.subject3
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private String subject3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade3
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private String grade3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.subject4
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private String subject4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade4
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    private String grade4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.idExaminee
     *
     * @return the value of grade.idExaminee
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public Integer getIdExaminee() {
        return idExaminee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.idExaminee
     *
     * @param idExaminee the value for grade.idExaminee
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setIdExaminee(Integer idExaminee) {
        this.idExaminee = idExaminee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.idperson
     *
     * @return the value of grade.idperson
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public String getIdperson() {
        return idperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.idperson
     *
     * @param idperson the value for grade.idperson
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setIdperson(String idperson) {
        this.idperson = idperson == null ? null : idperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.name
     *
     * @return the value of grade.name
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.name
     *
     * @param name the value for grade.name
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.subject1
     *
     * @return the value of grade.subject1
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public String getSubject1() {
        return subject1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.subject1
     *
     * @param subject1 the value for grade.subject1
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setSubject1(String subject1) {
        this.subject1 = subject1 == null ? null : subject1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade1
     *
     * @return the value of grade.grade1
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public String getGrade1() {
        return grade1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade1
     *
     * @param grade1 the value for grade.grade1
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setGrade1(String grade1) {
        this.grade1 = grade1 == null ? null : grade1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.subject2
     *
     * @return the value of grade.subject2
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public String getSubject2() {
        return subject2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.subject2
     *
     * @param subject2 the value for grade.subject2
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setSubject2(String subject2) {
        this.subject2 = subject2 == null ? null : subject2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade2
     *
     * @return the value of grade.grade2
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public String getGrade2() {
        return grade2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade2
     *
     * @param grade2 the value for grade.grade2
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setGrade2(String grade2) {
        this.grade2 = grade2 == null ? null : grade2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.subject3
     *
     * @return the value of grade.subject3
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public String getSubject3() {
        return subject3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.subject3
     *
     * @param subject3 the value for grade.subject3
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setSubject3(String subject3) {
        this.subject3 = subject3 == null ? null : subject3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade3
     *
     * @return the value of grade.grade3
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public String getGrade3() {
        return grade3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade3
     *
     * @param grade3 the value for grade.grade3
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setGrade3(String grade3) {
        this.grade3 = grade3 == null ? null : grade3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.subject4
     *
     * @return the value of grade.subject4
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public String getSubject4() {
        return subject4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.subject4
     *
     * @param subject4 the value for grade.subject4
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setSubject4(String subject4) {
        this.subject4 = subject4 == null ? null : subject4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade4
     *
     * @return the value of grade.grade4
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public String getGrade4() {
        return grade4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade4
     *
     * @param grade4 the value for grade.grade4
     *
     * @mbg.generated Fri Dec 14 14:23:28 CST 2018
     */
    public void setGrade4(String grade4) {
        this.grade4 = grade4 == null ? null : grade4.trim();
    }
}