package com.tiancheng.homework.domain;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.idnews
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    private Integer idnews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.timevalue
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    private String timevalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.path
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.idnews
     *
     * @return the value of news.idnews
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public Integer getIdnews() {
        return idnews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.idnews
     *
     * @param idnews the value for news.idnews
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public void setIdnews(Integer idnews) {
        this.idnews = idnews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.timevalue
     *
     * @return the value of news.timevalue
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public String getTimevalue() {
        return timevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.timevalue
     *
     * @param timevalue the value for news.timevalue
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public void setTimevalue(String timevalue) {
        this.timevalue = timevalue == null ? null : timevalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.path
     *
     * @return the value of news.path
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.path
     *
     * @param path the value for news.path
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}