package com.tiancheng.homework.domain;

public class Richeng {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column richeng.idricheng
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    private Integer idricheng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column richeng.title
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column richeng.timevalue
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    private String timevalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column richeng.path
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column richeng.idricheng
     *
     * @return the value of richeng.idricheng
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public Integer getIdricheng() {
        return idricheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column richeng.idricheng
     *
     * @param idricheng the value for richeng.idricheng
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public void setIdricheng(Integer idricheng) {
        this.idricheng = idricheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column richeng.title
     *
     * @return the value of richeng.title
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column richeng.title
     *
     * @param title the value for richeng.title
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column richeng.timevalue
     *
     * @return the value of richeng.timevalue
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public String getTimevalue() {
        return timevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column richeng.timevalue
     *
     * @param timevalue the value for richeng.timevalue
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public void setTimevalue(String timevalue) {
        this.timevalue = timevalue == null ? null : timevalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column richeng.path
     *
     * @return the value of richeng.path
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column richeng.path
     *
     * @param path the value for richeng.path
     *
     * @mbg.generated Sun Dec 16 20:16:47 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}