package com.tiancheng.homework.domain;

public class Server {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.idserver
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    private Integer idserver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.title
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.timevalue
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    private String timevalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.path
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.idserver
     *
     * @return the value of server.idserver
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    public Integer getIdserver() {
        return idserver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.idserver
     *
     * @param idserver the value for server.idserver
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    public void setIdserver(Integer idserver) {
        this.idserver = idserver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.title
     *
     * @return the value of server.title
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.title
     *
     * @param title the value for server.title
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.timevalue
     *
     * @return the value of server.timevalue
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    public String getTimevalue() {
        return timevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.timevalue
     *
     * @param timevalue the value for server.timevalue
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    public void setTimevalue(String timevalue) {
        this.timevalue = timevalue == null ? null : timevalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.path
     *
     * @return the value of server.path
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.path
     *
     * @param path the value for server.path
     *
     * @mbg.generated Sun Dec 16 20:55:24 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}